version: "3.9"
services:
  app:
    build: .
    ports: 
      - "5000:5000"
    volumes: 
      - /media/upload:/app/upload
    env_file: 
      - .env
    logging:
      driver: gelf
      options:
        gelf-address: udp://10.90.138.145:12201
        tag: app1
  web: 
    build: nginx
    ports:
      - "80:80"
    logging:
      driver: gelf
      options:
        gelf-address: udp://10.90.138.145:12201
        tag: nginx-app1